QDRANT_HOST = "127.0.0.1"
QDRANT_PORT = 6333
QDRANT_URL = f"http://{QDRANT_HOST}:{QDRANT_PORT}"

COLLECTION_NAME = "rag_docs"

EMBEDDING_DIM = 384

DATA_PATH = "./data/docs"

QDRANT_VECTOR_SIZE = 1024
