from enum import Enum


class ErrorType(str, Enum):
    NONE = "NONE"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    BUSINESS_RULE_FAILED = "BUSINESS_RULE_FAILED"
    RETRYABLE = "RETRYABLE"
    TIMEOUT = "TIMEOUT"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    MAX_STEPS_EXCEEDED = "MAX_STEPS_EXCEEDED"
    REPEAT_BLOCKED = "REPEAT_BLOCKED"
