"""global_model_check

Revision ID: 1eca888b5b5a
Revises: 98c8a9c8cea4
Create Date: 2026-05-25 12:51:30.293416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1eca888b5b5a'
down_revision: Union[str, Sequence[str], None] = '98c8a9c8cea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(length=200), nullable=False))
    op.alter_column('conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('conversations', 'tile')
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('conversations', sa.Column('tile', mysql.VARCHAR(length=200), nullable=True))
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
